;; AucTex mode
(require 'tex-site)
(add-hook 'LaTeX-mode-hook
          '(lambda ()
            (yas/minor-mode-off)
            (auto-fill-mode t)
            (whitespace-mode)
            (TeX-PDF-mode)
            (turn-on-reftex)
            (LaTeX-math-mode)
            ))
(setq TeX-view-program-list '(("Preview" "open %o")
                              ("Evince" "evince %o")))
(if (string-equal system-type "darwin")
    (setq TeX-view-program-selection '((output-pdf "Preview"))))
(if (string-equal system-type "gnu/linux")
    (setq TeX-view-program-selection '((output-pdf "Evince"))))
