;; Colors

;; set the font size
;; font-size is 1/10pt. 100 gives you 10pt
(set-face-attribute 'default nil :height 120)


;; (setq default-frame-alist
;;       '((top . 200) (left . 400)
;;         (width . 80) (height . 40)
;;         (cursor-color . "white")
;;         (cursor-type . box)
;;         (foreground-color . "yellow")
;;         (background-color . "black")
;;         (font . "-*-Courier-normal-r-*-*-13-*-*-*-c-*-iso8859-1")))

;; (setq default-frame-alist
;;       '((cursor-type . bar)
;;         ))

(setq default-frame-alist
      '(
        (top . 0)
        (left . 60)
        (width . 95)
        (height . 60)
        ))

(defun hp-set-font (frame)
  "Interval function"
  (set-frame-parameter frame 'font "Menlo-12")  
  )

(if (>= emacs-major-version 23)
    (hp-set-font frame-initial-frame)
)


(add-hook 'after-make-frame-functions
          'hp-set-font
          )

(defun hp-color()
  (interactive)
  (color-theme-install
   '(hp-color
     (
      (cursor-color . "turquoise")
      )
     ;; (mode-line ((t (:background "light gray" :foreground "black"))))
     (mode-line ((t (:background "turquoise" :foreground "black"))))
     ;; (mode-line-inactive ((t (:background "light gray10" :foreground "gray20"))))
     (mode-line-inactive ((t (:background "white" :foreground "gray20"))))

     ;; (font-lock-comment-face ((t (:slant italic :foreground "#254ED4"))))
     (region ((t (:background "#aaeeee"))))
     (font-lock-comment-face ((t (:slant italic :foreground "#0000FF"))))
     
     (font-lock-type-face ((t(:foreground "#22bb22"))))
     (font-lock-function-name-face ((t (:foreground "#000000" :weight bold))))
     (font-lock-keyword-face ((t (:foreground "#690593" :weight bold))))
     ;; (font-lock-keyword-face ((t (:foreground "#8B19BD" :weight bold))))
     (font-lock-doc-string-face ((t (:foreground "#FF234E"))))
     
     (font-lock-variable-name-face ((t (:foreground "#7e7d10"))))
     (font-lock-constant-face ((t (:foreground "#21857f"))))
     ))
  )

(provide 'hp-color)

(if window-system
    (progn
       (add-to-list 'load-path "/opt/local/share/emacs/site-lisp/color-theme-6.6.0")
       (require 'color-theme)
       (color-theme-initialize)
       (setq color-theme-is-global t)
       (hp-color)
      ))


(defun inspiration-hp1 ()
  "Theme generated by Sweyla: http://inspiration.sweyla.com/code/seed/289487/"
  (interactive)
  (color-theme-install
   '(inspiration-hp1
     ((background-color . "#FFFFFE")
      (foreground-color . "#000000")
      (background-mode . bright)
      (border-color . "#C8C8C8")
      (cursor-color . "#c0c0c0")
      (mouse-color . "#C8C8C8"))
     (mode-line ((t (:foreground "#000000" :background "#C8C8C8"))))
     (region ((t (:background "#C8C8C8"))))

     (font-lock-comment-face ((t (:foreground "#254ED4"))))
     (font-lock-constant-face ((t (:foreground "#823057"))))
     (font-lock-builtin-face ((t (:foreground "#3D46E5"))))
     (font-lock-function-name-face ((t (:foreground "#B0005A"))))
     (font-lock-variable-name-face ((t (:foreground "#001A66"))))
     (font-lock-keyword-face ((t (:foreground "#4520B4"))))
     (font-lock-string-face ((t (:foreground "#FF234E"))))
     (font-lock-doc-string-face ((t (:foreground "#FF234E"))))
     (font-lock-type-face ((t (:foreground "#460074"))))
     )))
(provide 'inspiration-hp1)

(defun inspiration-273632 ()
  "Theme generated by Sweyla: http://inspiration.sweyla.com/code/seed/273632/"
  (interactive)
  (color-theme-install
   '(inspiration-273632
     ((background-color . "#FFFFFF")
      (foreground-color . "#000000")
      (background-mode . bright)
      (border-color . "#C8C8C8")
      (cursor-color . "#000000")
      (mouse-color . "#C8C8C8"))
     (mode-line ((t (:foreground "#000000" :background "#C8C8C8"))))
     (region ((t (:background "#C8C8C8"))))

     (font-lock-comment-face ((t (:foreground "#240080"))))
     (font-lock-constant-face ((t (:foreground "#003F53"))))
     (font-lock-builtin-face ((t (:foreground "#000187"))))
     (font-lock-function-name-face ((t (:foreground "#FF5416"))))
     (font-lock-variable-name-face ((t (:foreground "#003991"))))
     (font-lock-keyword-face ((t (:foreground "#530CAE"))))
     (font-lock-string-face ((t (:foreground "#257D3D"))))
     (font-lock-doc-string-face ((t (:foreground "#257D3D"))))
     (font-lock-type-face ((t (:foreground "#009CEC"))))
     )))

(provide 'inspiration-hp2)
(defun inspiration-hp2 ()
  "Theme generated by Sweyla: http://inspiration.sweyla.com/code/seed/220192/"
  (interactive)
  (color-theme-install
   '(inspiration-220192
     ((background-color . "#FEFFFF")
      (foreground-color . "#000000")
      (background-mode . bright)
      (border-color . "#C8C8C8")
      (cursor-color . "#000000")
      (mouse-color . "#C8C8C8"))
     (mode-line ((t (:foreground "#000000" :background "#C8C8C8"))))
     (region ((t (:background "#C8C8C8"))))

     (font-lock-comment-face ((t (:foreground "#5F9373"))))
     (font-lock-constant-face ((t (:foreground "#5400C6"))))
     (font-lock-builtin-face ((t (:foreground "#344388"))))
     (font-lock-function-name-face ((t (:foreground "#B41DC4"))))
     (font-lock-variable-name-face ((t (:foreground "#4E35AA"))))
     (font-lock-keyword-face ((t (:foreground "#9456AB"))))
     (font-lock-string-face ((t (:foreground "#416A8F"))))
     (font-lock-doc-string-face ((t (:foreground "#416A8F"))))
     (font-lock-type-face ((t (:foreground "#0700FF"))))
     )))
(provide 'inspiration-hp2)
