;; load Emacs Speaks Statistics (ESS)
(load "~/.emacs_lib/ess-5.12/lisp/ess-site")
(require 'ess-site)

(defun ess-display-help-in-browser () 
  (interactive) 
  (if (not (equal ess-dialect "R")) 
      (message "Sorry, not available for the dialect %s " ess-dialect ) 
    (let ((object (buffer-name))) 
      (string-match ".*(\\(.*\\))[^)]*\\'" object) 
      (setq object (match-string 1 object)) 
      (if (not object) 
          (message "Cannot infer the help object from buffer name") 
        (ess-command (format "help('%s', help_type='html')\n" object)) 
        (message "Help for '%s' opened in the web-browser" object)) 
      ))) 

;; (define-key ess-help-mode-map "w" 'ess-display-help-in-browser) 

(add-hook 'ess-mode-hook
          '(lambda()
             (yas/minor-mode-on)
             (setq whitespace-line-column fill-column)
             (whitespace-mode)
             (ess-set-style 'C++ 'quiet)
             (setq ess-eval-visibly-p nil)
             (setq inferior-R-args "--no-save")
             (define-key ess-help-mode-map "w" 'ess-display-help-in-browser) 
             ;; (setq ess-help-own-frame 'one)
             ;; (setq ess-help-own-frame nil)
             ;; (setq inferior-ess-r-help-command "help(\"%s\", help_type=\"html\")\n")
             ))
